project:
  type: book

book:
  title: "Softwaredesign"
  date: last-modified
  reader-mode: true
  page-footer:
    left: Softwaredesign WS 2024 (MECH-M-DUAL-1-SWD)
    center: "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) Peter Kandolf"
    right: This book was built with <a href="https://quarto.org/">Quarto</a>.
  author:
    - name: "Peter Kandolf"
      orcid: 0000-0003-3601-0852
      affiliation: "MCI | The Entrepreneurial School"
  license: "CC BY-NC-SA"
  site-url: https://kandolfp.github.io/MECH-M-DUAL-1-SWD/
  repo-url: https://github.com/kandolfp/MECH-M-DUAL-1-SWD/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - part: basics/index.qmd
      chapters: 
        - basics/python.qmd
        - basics/packagemanager.qmd
        - basics/versioncontrol.qmd
        - basics/epilogue.qmd
    - part: pp/index.qmd
      chapters:
        - pp/oop.qmd
        - pp/fp.qmd
    - part: sc/index.qmd
      chapters:
        - sc/numpy.qmd
        - sc/pandas.qmd
    - part: errorhandling/index.qmd
      chapters:
        - errorhandling/exception.qmd
        - errorhandling/logging.qmd
        - errorhandling/testing.qmd
        - errorhandling/cicd.qmd
    - part: containerization/index.qmd
      chapters:
        - containerization/docker.qmd    
    - summary.qmd
    - references.qmd
  appendices:
    - sss/sss1.qmd
    - sss/sss2.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: [flatly, style.css]
      dark: [darkly, dark-style.css]
    mermaid:
      theme: neutral
#  pdf:
#    documentclass: scrreprt



