on:
  workflow_dispatch:
  push:
    branches: main

name: Testing

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up PDM
          uses: pdm-project/setup-pdm@v4
        - name: Install dependencies
          run: |
            pdm sync
        - name: Run Tests
          run: |
            pdm run -v pytest tests
